//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentMasterAPI.Models
{
    using System;
    
    public enum TournamentType : int
    {
        SingleElimination = 0,
        DoubleElimination = 1,
        RoundRobin = 2,
        Swiss = 3
    }
}
