//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentMasterAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentMasterDataAccessContainer : DbContext
    {
        public TournamentMasterDataAccessContainer()
            : base("name=TournamentMasterDataAccessContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Competitor> Competitors { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Pairing> Pairings { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Tournament> Tournaments { get; set; }
    }
}
