//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentMasterDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pairing
    {
        public int Id { get; set; }
        public int RoundId { get; set; }
        public int Result { get; set; }
        public int CompetitorId1 { get; set; }
        public int CompetitorId2 { get; set; }
    
        public virtual Round Round { get; set; }
        public virtual Competitor Competitor1 { get; set; }
        public virtual Competitor Competitor2 { get; set; }
    }
}
